---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.0.2
    entrypoint: [""]
  variables:
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack
  script:
    - make clean check build test doc exec
    - mv $(stack path --local-install-root)/doc/fizzbuzz-*/ public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .stack
      - .stack-work

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publishing documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
