---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:8.10.7
    entrypoint: [""]
  variables:
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack
  script:
    - make setup clean check build test doc exec
    - mv $(stack path --local-doc-root) public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .stack
      - .stack-work

pages:
  stage: deploy
  only:
    refs:
      - master
  dependencies:
    - build
  image: alpine:latest
  script:
    - echo Publishing pages ...
  artifacts:
    paths:
      - public
