# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt-get install -y make ghc cabal-install haskell-stack
    stack setup
  displayName: dependencies

- script: |
    stack build
  displayName: build

- script: |
    stack test --coverage
  displayName: test
